import Head from 'next/head';
import { ReactElement } from 'react';
import Header from '../components/Header';
import styled from 'styled-components';

const Container = styled.div`
  width: 100vw;
  min-height: 100vh;
`;

/**
 * Main page
 */
export default function Home(): ReactElement {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet"/>
      </Head>

      <Header/>
    </Container>
  );
}
